### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by telegrambotdev** [gaowanliang/DownloadBot#1]
1.Upload to telegram after torrent finishes.if the files is larger than 2gb,it must split and then upload to tg by parts

2.Need ZIP option to compress downloaded files before uploading to cloud (most wanted)

3. Need RCLONE support too,then we can add gdrive,onedrive..everything in one simple setup

4.if you can add ytdl-org code support too..for downloading videos

**Comment by gaowanliang** [comment]
1.Since telegram limits the size of uploaded files and it is not convenient to manage files, the plan for uploading to telegram will be processed after the upload function of OneDrive, Google drive and other online disks is completed.
2.This feature will be added in the future. The original intention of this project is to download files on a server with a small hard disk. If you're packing files, the size of the torrent file for each download needs to be weighed appropriately. This is more difficult for servers with small hard disk.
3.Now I have developed the function of moving files(It is still in testing and is not public). You can use rclone to mount your network disk and then directly move the files to the mounted location. The support of the network disk described for the list only corresponds to the support of the API provided by them, so that the upload function can be achieved without installing any other software.
4.In the future, similar functions may be supported in the form of plug-ins.
